//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MusicPlanner.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MusicMasterEntities : DbContext
    {
        public MusicMasterEntities()
            : base("name=MusicMasterEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Choir> Choir { get; set; }
        public virtual DbSet<NewMonthlyMusic> NewMonthlyMusic { get; set; }
        public virtual DbSet<Files> Files { get; set; }
    }
}
