//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MusicPlanner
{
    using System;
    using System.Collections.Generic;
    
    public partial class NewMonthlyMusic
    {
        public int MusicID { get; set; }
        public System.DateTime Date { get; set; }
        public string churchDay { get; set; }
        public string Opening { get; set; }
        public string OpeningNumber { get; set; }
        public string Psalm { get; set; }
        public string PsalmNumber { get; set; }
        public string Preparation { get; set; }
        public string PreparationNumber { get; set; }
        public string Communion { get; set; }
        public string CommunionNumber { get; set; }
        public string Closing { get; set; }
        public string ClosingNumber { get; set; }
        public string Notes { get; set; }
    }
}
